### ISSUE TITLE
 Define the product vision

### ISSUE THREAD

**Issue by athrael-soju** [athrael-soju/whisperChat#75]

**Comment by Olga-Topchaya** [comment]
whisperChat supports team collaboration by helping to analyze documents and explain them. It's tailored to the employee's domain and level of familiarity with a topic. It remembers all the conversations the employee had with it which adds to its personalization capabilities. 
Being voice to voice means a person can use it while commuting, exercising or multi-tasking, etc., thereby saving time.

A company will upload their documents to whisperChat and employees can ask questions of other departments' documents. For example, a lawyer can ask questions about their company's finances and can draft contracts taking the financial obligations into account. A marketer can undertand their company's products better when working with engineers by asking questions from technical specification documents.
So when they have team meetings or projects they need to collaborate on together, they can now have productive conversations because they have more nuanced understanding of each other's work.
